name: engtrhukuksozluk
description: A new Flutter application.

version: 1.0.4+9

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  like_button: ^0.2.0
  firebase_core: ^0.4.4
  firebase_analytics: ^5.0.11
  firebase_database: ^3.1.1
  firebase_crashlytics: ^0.1.3+3
  firebase_messaging: ^6.0.13
  flip_card: ^0.4.4
  cloud_firestore: ^0.13.4
  algolia: ^0.1.7
  floor: ^0.11.0
  sqflite: any
  animated_text_kit: ^2.0.0
  url_launcher: ^5.4.2
  google_fonts: ^0.3.10
  animations: ^1.0.0+5
  auto_animated: ^2.0.2
  flutter_tts: ^0.9.1
  intro_slider: ^2.2.9
  shared_preferences: ^0.5.6+3
  flutter_native_admob: ^2.1.0
  flutter_screenutil: ^1.1.0
  circle_bottom_navigation: ^1.0.5
  auto_size_text: ^2.1.0
  simple_animations: ^1.3.3
  get: ^3.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^0.11.0
  build_runner: ^1.7.3
  effective_dart: ^1.2.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - images/
  - google_fonts/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #fonts:
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
